#!/bin/bash
#Note: You have to give permission with the chmod command before you cun run this script
#RTFM if you don't know how :)
mkdir Galvanize
cd Galvanize
mkdir Frontend
cd Frontend
mkdir CSS-Framework
mkdir CSS-Responsive-Pages
mkdir CSS-Style-HTML
mkdir CSS-with-SASS
mkdir Client-Side-Build-Tools
mkdir Concepts
mkdir DOM-Coding
mkdir DOM-JSON-with-AJAX
mkdir DOM-Unit-Tests-with-Mocha
mkdir HTML-Valid-and-Semantic
mkdir HTTP-Concepts
cd ..
mkdir Problem-Solving
cd Problem-Solving
mkdir Polya-at-Whiteboard
mkdir Polya-with-Algorithms
cd ..
mkdir Productivity
cd Productivity
mkdir Command-Line-FS
mkdir Git-Amend
mkdir Git-Bisect
mkdir Git-Filter-Branch
mkdir Git-Rebase
mkdir Git-Remotes
mkdir Git-Stash
mkdir Git-and-Github
mkdir Git-for-Teams
mkdir VIM
cd ..
mkdir Programming
cd Programming
mkdir Accumulator-Pattern
mkdir Big-0-Level-1
mkdir Big-0-Level-2
mkdir Big-0-Level-3
mkdir JS-Concepts
mkdir JS-Expressions
mkdir JS-Functional-Iteration
mkdir JS-Functions
mkdir JS-Higher-Order-Functions
mkdir JS-Promises
mkdir JS-Spread-and-Arguments
mkdir JS-Tests-with-Mocha
mkdir Linked-Lists
mkdir Recursive-Iteration
mkdir Refactor-to-DRY
mkdir Refactor-to-SRP
mkdir Swapping-and-Sorting
mkdir TDD-Unit-Test
mkdir Tree-Traversal
mkdir Unfamiliar-Languages
cd ..
mkdir Agile
cd Agile
mkdir Concepts
mkdir Retrospectives
mkdir Stories
mkdir Workflow
cd ..
mkdir Server-Side
cd Server-Side
mkdir Applications
mkdir Associations
mkdir Auth-Concepts
mkdir Authentication-and-Authorization
mkdir CRUD-in-Other-Language
mkdir CRUD-with-Single-Resource
mkdir Deploy-to-AWS-with-AMI
mkdir ERD
mkdir Feature-Test-Server-Side-App
mkdir Harden-for-Security
mkdir RESTful-API
mkdir Refactor-Server-Side-App
mkdir SQL
mkdir Test-Server-Side-App
mkdir Validations
mkdir Web-Sockets
cd ..
mkdir Deployment
cd Deployment
mkdir AWS-Install-APP-with-Script
mkdir AWS-Provision-Server-with-Script
mkdir Client-Server-App-with-CORS
mkdir Cloud-Foundry-Deploy-Server-App
mkdir Cloud-Foundry-Deploy-Static-App
mkdir Continuously-Deploy-App
mkdir Database-App-to-Heroku
mkdir Fullstack-SPA
mkdir Static-Site
cd ..
mkdir OOP
cd OOP
mkdir Constructor-Functions
mkdir Explain-Pillars
mkdir Factory-Functions
mkdir Mentally-Evaluate
mkdir Refactor-to-Pillars
mkdir Speak-Fluently
mkdir State-and-Behavior
mkdir Static-Types
cd ..
mkdir Career-Services
cd Career-Services
mkdir Behavioral-Questions
mkdir Compensation-Questions
mkdir Describe-Galvanize
mkdir Describe-Project
mkdir One-Contact-per-Week
mkdir Organize-Job-Applications
mkdir Prepare-for-Interview
mkdir Present-Yourself
mkdir Resume
mkdir Set-Your-Intention
mkdir Social-Media-Presence
mkdir Verbal-Introduction
cd ..
mkdir Single-Page-Applications
cd Single-Page-Applications
mkdir Angular-CRUD-App
mkdir Angular-Components
mkdir Angular-Token-Auth
mkdir Angular-with-Routes
mkdir React-CRUD-App
cd ..
cd ..
